apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-keycloak
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: policy-keycloak
        spec:
          remediationAction: enforce
          severity: medium
          complianceType: musthave
          subscription:
            name: rhbk-operator
            namespace: keycloak
            channel: stable-v26.2
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
          operatorGroup:
            name: default
            targetNamespaces:
              - keycloak
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-keycloak-placement
  namespace: policies
placementRef:
  name: hub-infra-operators-placement-1
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-keycloak
    apiGroup: policy.open-cluster-management.io
    kind: Policy
