apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gitops-operator
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: policy-gitops-operator
        spec:
          remediationAction: inform
          severity: medium
          complianceType: musthave
          subscription:
            name: openshift-gitops-operator
            namespace: openshift-gitops-operator
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
          operatorGroup:
            name: default
            targetNamespaces:
              - openshift-gitops-operator
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-gitops-operator-placement
  namespace: policies
placementRef:
  name: hub-infra-operators-placement-1
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-gitops-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
