#!/bin/bash

echo "--- Interactive GitHub Secret Creation ---"
echo "This script will guide you through creating a Kubernetes Secret YAML file."
echo "--------------------------------------------------------------------------"

while [ -z "$GITHUB_USER" ]; do
  read -p "Enter your GitHub username: " GITHUB_USER
done

while [ -z "$GITHUB_TOKEN" ]; do
  read -sp "Enter your GitHub Personal Access Token (PAT): " GITHUB_TOKEN
  echo ""
done

read -p "Enter a name for the Kubernetes Secret [github-acm-credentials]: " SECRET_NAME
SECRET_NAME=${SECRET_NAME:-"github-acm-credentials"}

read -p "Enter the Kubernetes namespace for the secret [policies]: " KUBE_NAMESPACE
KUBE_NAMESPACE=${KUBE_NAMESPACE:-"policies"}

echo "--------------------------------------------------------------------------"
echo "Generating YAML file with the following details:"
echo "Secret Name:     $SECRET_NAME"
echo "Namespace:       $KUBE_NAMESPACE"
echo "GitHub Username: $GITHUB_USER"
echo "--------------------------------------------------------------------------"

ENCODED_USER=$(echo -n "$GITHUB_USER" | base64)
ENCODED_TOKEN=$(echo -n "$GITHUB_TOKEN" | base64)

FILENAME="${SECRET_NAME}-secret.yaml"

cat <<EOF > "$FILENAME"
# This file was generated by the create_git_secret.sh script
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
  # These values are Base64 encoded
  user: ${ENCODED_USER}
  accessToken: ${ENCODED_TOKEN}
EOF

echo ""
echo -e "\033[0;32mSUCCESS!\033[0m"
echo "The YAML file has been created with the name: ${FILENAME}"
echo ""
echo "You can now apply it to your cluster with the command:"
echo "oc apply -f ${FILENAME}"
echo "--------------------------------------------------------------------------"