---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-dr-local-storage
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      matchLabels:
        local-cluster: 'true'
  # remediationAction: inform
  remediationAction: enforce
  # complianceType: mustonlyhave
  complianceType: musthave
policies:
  - name: policy-dr-local-storage
    manifests:
      - path: 01_namespace.yaml
      - path: 02_operatorgroup.yaml
      - path: 03_subscription.yaml
      #- path: 04_localvolume.yaml