apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-local-storage-operator
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/description: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name: openshift-local-storage
            namespace: openshift-local-storage
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-local-storage-operator-placement
  namespace: policies
placementRef:
  name: place-on-hub
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-local-storage-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
